### ISSUE TITLE
Use zip file and powershell Expand-Archive if 7zip isn't available

### ISSUE THREAD

**Issue by John-Colvin** [mihails-strasuns/dc#7]
Anyone with powershell 5.0 and up will have Expand-Archive, which by now is pretty much everyone.

**Comment by mihails-strasuns** [comment]
Unless I am missing something, LDC does not provide zip distribution for Windows: https://github.com/ldc-developers/ldc/releases

**Comment by John-Colvin** [comment]
Yeah, true, I didn't sport that.

Nonetheless, it's always good to have things just work out of the box when they can.

I guess 7zip as a library would solve it for all cases.

**Comment by mihails-strasuns** [comment]
Yup, that is the plan.
